### ISSUE TITLE
camelCase column names in bigquery break copies

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#100]
If you have a camelCase column name, you will get an error like:

```
Error: could not find column subscriptionpayment in BigQuery table myproject-123:mydataset.myorders
```

I assume this is because it is treating column names as case-insensitive but they really aren't

**Comment by seamusabshere** [comment]
finding more examples of this

**Comment by emk** [comment]
Duplicate of #84.
