### ISSUE TITLE
Unable to export postgres schema as bq: Found argument which wasn't expected

### ISSUE THREAD

**Issue by mikebridge** [faradayio/dbcrossbar#106]
With version 0.3.0 I can't seem to export a postgresql schema as per the [example](https://github.com/faradayio/dbcrossbar#examples)

```
$ dbcrossbar postgres://user:password@localhost:5432/salocal#accounts_user -O bq:schema
error: Found argument 'postgres://user:password@localhost:5432/salocal#accounts_user' which wasn't expected, or isn't valid in this context
```

**Comment by emk** [comment]
My apologies! That section of the README is simple wrong. Try:

```
dbcrossbar conv postgres://user:password@localhost:5432/salocal#accounts_user bigquery-schema:schema.json
```

Somehow that section of the README didn't get updated when the CLI changed. I'll fix this in the next release. Thank you!

**Comment by mikebridge** [comment]
Great, thanks!  This is a super-useful project BTW.
