### ISSUE TITLE
`*_locator` logs leak URL password

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#15]
url parse 'em out

no reason to ever log them, even at RUST_LOG=debug

**Comment by emk** [comment]
Yeah, this requires fixing some `Display` and `Debug` methods on `Locator` implementations. It's on the list.

But in the meantime, please don't run in production with logging turned up.

**Comment by seamusabshere** [comment]
@emk this happens even at RUST_LOG=warn

remember, it's added to the log context

```
        // Build a logging context.
        let ctx = ctx.child(o!(
            "from_locator" => opt.from_locator.to_string(),
            "to_locator" => opt.to_locator.to_string(),
        ));
```

**Comment by seamusabshere** [comment]
fixed by https://github.com/faradayio/dbcrossbar/commit/84358c5e6b68d75d1a83c7dc3092f492005b07b6
