### ISSUE TITLE
automatic handling of env vars, boto configs, etc.

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#23]
i should just be able to point dbcrossbar at a gcloud keyfile and it should do the rest in terms of writing boto config files, setting BOTO_CONFIG, etc.

**Comment by emk** [comment]
Honestly, as long as we're shelling out to `gsutil`, I would strongly prefer to use 100% standard `gsutil` configuration, even if it's ugly. This simplifies `dbcrossbar`'s code considerably, and allows us to troubleshoot by troubleshooting `gsutil`.

Now, if we want to _get rid_ of `gsutil` entirely, that's a very interesting subject, and it would allow us to tackle many other problems with regard to memory usage, setup headaches, etc.

**Comment by seamusabshere** [comment]
good point
