### ISSUE TITLE
bigquery null text array is converted to postgres empty text array

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#24]
bigquery REPEATED STRING `null`

becomes

postgres text[] `{}`

expected

postgres text[] `null`

**Comment by emk** [comment]
I _think_ BigQuery arrays are never actually `NULL`, just empty, but I don't have easy access to the docs right now, and IIRC there are some missing docs related to this. BigQuery arrays are just _weird_.

**Comment by seamusabshere** [comment]
sure - but an empty array should be converted into a null array in postgres, right?

**Comment by emk** [comment]
@seamusabshere It's ambiguous, and there's no one right answer. The array of zero elements `[]` and the absence of an array `NULL` are represented in exactly the same way in BigQuery, IIRC. So when I translate to a CSV file (for loading into PostgreSQL), I have to pick one or the other. No matter which I pick, it will be wrong for some use cases.

We could collect arguments in favor of each case, and pick whichever representation worked better in the average case. But the current choice is the simple choice that doesn't involve extra messing around with external procedures. However, simple isn't necessarily correct, and I'd be happy to reconsider.

**Comment by seamusabshere** [comment]
i think there are 2 strong arguments that empty bigquery should go to null postgres:

1. least surprise. nobody expects emptiness (very similar to nullness) to be represented in postgres with `[]`.
2. roundtripability. you always lose nullness if you go through bigquery (which is exactly what's happening to me right now)

**Comment by emk** [comment]
Yeah, you _definitely_ lose some data subtleties if you round-trip through BigQuery. It has a much more restrictive data model than PostgreSQL.

The trick is figuring out the Right Answer for each issue, once, and then reusing it everywhere.

This is actually not PostgreSQL-related at all; it affects whether BigQuery exports an empty `ARRAY<..>` as `,,` or `,[],` in the BigQuery->CSV conversion. And we could definitely do that. The actual code in question is here (in the 0.2.x branch, not the 0.1.x branch you need) and it's pretty simple: https://github.com/faradayio/dbcrossbar/blob/c085a996bfce8abc3414f46434af2ea0c2868288/dbcrossbarlib/src/drivers/bigquery_shared/column.rs#L252-L293

Probably we would need replace the `TO_JSON_STRING` wrapper with something a bit more clever. This could be an inline expression or a pure-SQL UDF.
