### ISSUE TITLE
multiple local csvs to bigquery

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#28]

**Comment by emk** [comment]
This requires updating https://github.com/faradayio/dbcrossbar/blob/48ed3252c6ecd5a6ec192da9291c70bbac5e2870/dbcrossbarlib/src/drivers/csv/mod.rs#L102-L143 to work more like https://github.com/faradayio/dbcrossbar/blob/master/dbcrossbarlib/src/drivers/s3/local_data.rs.

This is an excellent pairing opportunity and we should use it as such if it's not urgent.
