### ISSUE TITLE
redshift source fails on copy command

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#41]
```
INFO:  Table "customers" does not exist and will be skipped
INFO:  Load into table 'customers' completed, 100 record(s) loaded successfully.
Error: db error: ERROR: syntax error at or near "("
```

**Comment by seamusabshere** [comment]
i believe this is redshift not supporting `COPY FROM (x)`

**Comment by emk** [comment]
Yes. I'm remerging this with #26, and I'm going to tackle all the RedShift stuff together early next week, as discussed there, probably using a quick and dirty Avro converter for loading and CSV for dumping.
