### ISSUE TITLE
upserting rows with null keys results in duplicates

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#43]
let's say you have 2 upsert columns (part1 and part2). if you `--if-exists=upsert-on:part1,part2`, but part2 (for example) is sometimes null, you will get a duplicate row every time you run the cp.

it's possible to "fix" this behavior by replacing nulls with a 0xDEADBEEF value.

```
CREATE TABLE tmp.test_receiver (
  part1 string,
  part2 string,
  color string
);

insert into tmp.test_receiver (part1, part2, color)
values
('seamus', 'abshere', 'red'),
('prithaj', 'nath', 'green'),
('eric', null, 'blue')

CREATE TABLE tmp.test_sender (
  part1 string,
  part2 string,
  color string
);

insert into tmp.test_sender (part1, part2, color)
values
('seamus', 'abshere', 'rojo'),
('prithaj', 'nath', 'verde'),
('eric', null, 'azul'),
('andy', null, 'marron');

CREATE TABLE  tmp.safe_sender AS (
  SELECT
    *
    REPLACE (
      COALESCE(part1, '0xDEADBEEF') AS part1,
      COALESCE(part2, '0xDEADBEEF') AS part2
    )
  FROM tmp.test_sender
);


MERGE INTO tmp.test_receiver AS dest
USING tmp.safe_sender AS source
ON
    COALESCE(dest.part1, '0xDEADBEEF') = source.part1
AND COALESCE(dest.part2, '0xDEADBEEF') = source.part2
WHEN MATCHED THEN
  UPDATE SET color = source.color
WHEN NOT MATCHED THEN
  INSERT (part1, part2, color) VALUES (source.part1, source.part2, source.color)
```

there are 2 problems with this approach:

1. the code that generates the MERGE must know about the table structure and generate a temporary table (cannot be inlined with CTEs) with lots of REPLACEs...
2. ...and while it's obvious what to replace a string with ("0xDEADBEEF", nobody is going to mistake that for real data), it's not obvious what to replace numerics with. For example, if you are upserting against a numeric column and you, as part of this upsert correction process, replace nulls with -1, then suddenly your column's average will change, etc.

It's possible we should just require users be aware of this, but in case we want to be opinionated and solve it, ⬆️ is one idea for doing so. SQL is tested and works on bigquery.

**Comment by emk** [comment]
Hmm, I need to look at this in more detail. There must be _some_ principled solution for this at the SQL level, you'd think.

Can we get reasonable behavior with something like `IS NULL` or `IS NOT NULL`, perhaps as part of a more complex expression?

**Comment by emk** [comment]
(Still on my phone, so take this with a grain of salt.)

Ah, here we go. I think maybe we're looking for something like this, if I understand your big report correctly? https://modern-sql.com/feature/is-distinct-from

I don't think this is supported by BigQuery, but there's a portable workaround mentioned that we could try.

**Comment by emk** [comment]
So, in theory, I'd think that [the workaround solution](https://modern-sql.com/feature/is-distinct-from) would solve our problems:

```sql
CREATE TEMP FUNCTION ImportJson_3(input STRING)
RETURNS ARRAY<STRING>
LANGUAGE js AS """
return JSON.parse(input);
""";

MERGE INTO `root-180513.test.bigquery_upsert` AS dest
USING `root-180513.test.temp_bigquery_upsert_5HVQeBXGlv` AS temp
ON
    CASE WHEN (dest.`key1` = temp.`key1`) OR (dest.`key1` IS NULL AND temp.`key1` IS NULL) THEN 0 ELSE 1 END = 0 AND
    CASE WHEN (dest.`key2` = temp.`key2`) OR (dest.`key2` IS NULL AND temp.`key2` IS NULL) THEN 0 ELSE 1 END = 0
WHEN MATCHED THEN UPDATE SET
    `value` = temp.`value`,
    `more` = ImportJson_3(temp.`more`)
WHEN NOT MATCHED THEN INSERT (
    `key1`,
    `key2`,
    `value`,
    `more`
) VALUES (
    temp.`key1`,
    temp.`key2`,
    temp.`value`,
    ImportJson_3(temp.`more`)
)
```

This, however fails with the following error:

> **RIGHT OUTER JOIN cannot be used without a condition that is an equality of fields from both sides of the join.**

We also get this error with:

```sql
ON
    ((dest.`key1` = temp.`key1`) OR (dest.`key1` IS NULL AND temp.`key1` IS NULL)) AND
    ((dest.`key2` = temp.`key2`) OR (dest.`key2` IS NULL AND temp.`key2` IS NULL))
```

Weirdly,

```sql
ON
    COALESCE(dest.`key1`, 99) = temp.`key1`
```

...actually does pass the syntax check. But the `0xDEADBEEF` kludge requires re-purposing a perfectly-valid value as a sentinel value, which is just too ugly to be acceptable.

I think the real answer here is that BigQuery can't `UPSERT` on potentially `NULL` columns, which isn't horribly surprising—compound primary keys containing `NULL` values are a genuinely horrible idea.

So probably the best solution, from a correctness standpoint, is to also allow `upsert-on` to be used on columns which are declared `NOT NULL`.
