### ISSUE TITLE
dbcrossbar cp ignores nullability set in --schema when creating bigquery table

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#45]
i create a table like this:

```
dbcrossbar cp --temporary=gs://tmp   --temporary=bigquery:myproject:tmp   --if-exists=overwrite   --schema dbcrossbar-schema:spec/support/files/northwind_customers.dbcrossbar_schema.json spec/support/files/northwind_customers.csv bigquery:myproject:northwind.customers
```

my spec contains this:

```
{
  "name": "fdytest-244019:northwind.customers",
  "columns": [
    {
      "name": "id",
      "is_nullable": false,
      "data_type": "int64"
    },
[...]
```

but the resulting table on bigquery has id as nullable:

<img width="431" alt="Screen Shot 2019-07-26 at 11 31 41 AM" src="https://user-images.githubusercontent.com/15787/61963158-07f71080-af99-11e9-9300-6b7eb01dec98.png">

**Comment by seamusabshere** [comment]
i tried this with a postgres-sql and it doesn't work either:

```
CREATE TABLE "myproject:northwind.customers" (
    "id" bigint not null,
    "first" text,
    "last" text,
    "address" text,
    "city" text,
    "state" text,
    "d_int1" bigint,
    "d_float1" double precision,
    "d_string1" text,
    "d_bool1" boolean,
    "d_date1" date
);

```

**Comment by seamusabshere** [comment]
@emk what are your thoughts on this?

**Comment by emk** [comment]
This is a confirmed real bug, which occurs because we create the final table using `bq query` and a `SELECT` statement, which automatically marks all the output columns as `NULLABLE`. See #68 for some unit tests and a more detailed explanation.
