### ISSUE TITLE
no way to override REQUIRED check on upsert-keys

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#59]
let's say you have a legacy table with a NULLABLE column (e.g. `model_id`) that you want to use as an upsert key. you will get this error:

```
Error: BigQuery cannot upsert on "model_id" because it is not REQUIRED (aka NOT NULL)
```

you can't change NULLABLE->REQUIRED.

so we need a flag (i think) like `--allow-nullable-upsert`

**Comment by seamusabshere** [comment]
i cut a temporary release to route around this https://github.com/faradayio/dbcrossbar/releases/tag/v0.2.1-seamus.1

**Comment by emk** [comment]
The current recommend workaround to this is to supply a `--schema` which promises that the upsert key columns are `NOT NULL`. If you do this, `dbcrossbar` will currently believe you.
