### ISSUE TITLE
dbcrossbar cp csv directory -> "Is a directory" error

### ISSUE THREAD

**Issue by fwallacevt** [faradayio/dbcrossbar#62]
```
dbcrossbar cp csv:/tmp/my-tmp-dir/ s3://my-bucket/my-prefix/ --if-exists overwrite
```
fails when I leave the source as a directory, with error:
```
Error: error reading /tmp/my-tmp-dir/ caused by: Is a directory (os error 21)
```

However, there is (or was) a file in that directory, and when I run
```
dbcrossbar cp csv:/tmp/my-tmp-dir/my-file.csv s3://my-bucket/my-prefix/ --if-exists overwrite
```
it succeeds. This is just trying to copy from a local directory to an S3 bucket, so no schema necessary. Is this a bug with `dbcrossbar`? Given a directory, is it expected to locate files within that and copy them up?

**Comment by seamusabshere** [comment]
@emk says this is because dbcrossbar is expecting a schema, and it's reporting the wrong error
