### ISSUE TITLE
quote individual parts of bigquery table locators, not the whole thing together

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#79]
what dbcrossbar currently generates, which is invalid:

```
SELECT `id` FROM `myproject-123.tmp.mytable` WHERE mytable.batch_id = '75c600c4-6da3-47f2-8e6f-893be683ef76'
```

what dbcrossbar could generate, which is valid:

```
SELECT `id` FROM `myproject-123`.`tmp`.`mytable` WHERE mytable.batch_id = '75c600c4-6da3-47f2-8e6f-893be683ef76'
```

in other words, please quote the 3 parts of the table locator separately

**Comment by n1ywb** [comment]
Might be worth noting that `.` still needs to be backwhacked inside quoted identifiers or BQ will error.

**Comment by emk** [comment]
Huh, fun. We have a whole bunch of machinery for dealing with this garbage but I guess we missed some places? Fun.
