### ISSUE TITLE
copying bigquery `TEXT` to postgres `UUID` gives unreadable error (e.g. 0xf2 0x43 0xad 0x46)

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#80]
if you copy bigquery TEXT to postgres UUID, you get this error

```
ERROR: invalid byte sequence for encoding "UTF8": 0xf2 0x43 0xad 0x46
```

dbcrossbar should probably detect that it's trying to copy bigquery text into postgres uuid and throw an error

(note to users who run into this: you can fix this by passing `--schema` with a schema that says the columns in question are uuids)

**Comment by emk** [comment]
Please verify that this issue still exists in v0.2.7.

We currently do the following:

1. Call `PgCreateTable::from_pg_catalog` to load the _actual_ column information from the database, and we align it with the schema provided on the command line. ([here](https://github.com/faradayio/dbcrossbar/blob/331fa730a428a75df5db901ba380bac4f088c4ee/dbcrossbarlib/src/drivers/postgres/write_local_data.rs#L251-L255))
2. Use real-but-realigned schema to drive the `BINARY` conversion ([here](https://github.com/faradayio/dbcrossbar/blob/331fa730a428a75df5db901ba380bac4f088c4ee/dbcrossbarlib/src/drivers/postgres/write_local_data.rs#L271-L280)).

So this _should_ have been fixed when we fixed the whole `json` versus `jsonb` issue. Are you using an up-to-date `dbcrossbar`?

**Comment by seamusabshere** [comment]
i think this is probably fixed, i haven't seen it in a long time
