### ISSUE TITLE
--read-schema-from-destination would be nice

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#90]
For example, if you're copying from BigQuery to Postgres, you might get:

```
caused by: db error: ERROR: invalid byte sequence for encoding "UTF8": 0x00
```

In order to fix this, you have to manually read the schema from Postgres using `dbcrossbar conv` and then feed it back into the `dbcrossbar cp` command. It would be nice if I could just tell dbcrossbar to do this for me.

**Comment by emk** [comment]
This looks like it might be a dup of #85. Whatever is causing this problem is not something that's appropriately addressed by adding the suggested flag, I don't think.

**Comment by seamusabshere** [comment]
this is what i wanted:

```
postgres=# create table a (id text);
CREATE TABLE

postgres=# create table b (id uuid);
CREATE TABLE

postgres=# insert into a (id) values (uuid_generate_v4()::text);
INSERT 0 1

$ dbcrossbar cp $DATABASE_URL#a $DATABASE_URL#b --if-exists overwrite

postgres=# select * from b;

                  id
--------------------------------------
 501e479a-c6e4-4fe6-b0c9-eeb09acd9ccc
(1 row)
```

that's with 0.2.9. i think we're good!
